### ISSUE TITLE
Create Root Certificate in Key Vault

### ISSUE THREAD

**Issue by mkreidenweis** [estiller/build-pki-net-azure-sample#1]
Hi @estiller 

thanks for the presentation on "Create Your Own Serverless PKI with .NET & Azure Key Vault". It really pointed out some important things. :-)

Regarding
https://github.com/estiller/build-pki-net-azure-sample/blob/c26353c99763971c730aba322874dc1b68fb001d/BuildPkiSample.Setup/RootCertificateHelper.cs#L69
I'm happy to let you know there is actually a way to create CA certificates inside Key Vault with a non-exportable private key. It's just not documented very well, and not available through client libraries, only through the REST API.

I wrote about it in more detail here:
https://stackoverflow.com/a/60044977/12749249
https://github.com/Azure/azure-rest-api-specs/issues/8295

Actually the documentation has gotten even worse since I wrote that: The [D509 Props Documentation Link](https://docs.microsoft.com/en-us/rest/api/keyvault/certificates-and-policies#d509-props) that I'm referring to in the links above, is now also gone.

**Comment by estiller** [comment]
Hi @mkreidenweis ,
Thanks for pointing this out! 

I know that linked page that is missing. I also found it at the time, and I even discussed it with the Azure Key Vault team. They told me it is an old irrelevant page, and they removed it afterward. I was explicitly told that this behavior was not supported at the time. I also tried to manually craft the request using the REST API and the documentation which was available on that page, but it didn't work at the time for sure. Perhaps they changed this behavior since then?
Are you sure this code works?

**Comment by mkreidenweis** [comment]
>  Are you sure this code works?

Yes, I was using Postman when I first tried this. The openssl dump extract on the Stackoverflow answer is actually what I got after exporting the certificate from Key Vault. 

Right now we're using Powershell `Invoke-WebRequest` to post JSON like that to `"https://${keyVaultName}.vault.azure.net/certificates/${certificateName}/create?api-version=7.0"`:
```json
{
  "policy": {
    "x509_props": {
      "subject": "CN=Custom Root CA",
      "sans": {
        "dns_names": []
      },
      "validity_months": 240,
      "ekus": [],
      "basic_constraints": {
        "ca": true,
        "path_len_constraint": 2
      },
      "key_usage": [
        "keyCertSign",
        "cRLSign"
      ]
    },
    "secret_props": {
      "contentType": "application/x-pkcs12"
    },
    "issuer": {
      "name": "Self"
    },
    "key_props": {
      "kty": "RSA",
      "key_size": 2048,
      "exportable": false,
      "reuse_key": false
    }
  }
}
```

And we can get certificates signed by Key Vault with code similar to yours:
https://github.com/estiller/build-pki-net-azure-sample/blob/fa8ccf016bfce7cc121cd1669a03134d61f37ba6/BuildPkiSample.CertificateAuthority.BusinessLogic/CertificateIssuer.cs#L27

**Comment by estiller** [comment]
Thanks, @mkreidenweis!
I'll try and check it out soon, and maybe revamp the sample.

**Comment by estiller** [comment]
Hi @mkreidenweis,
I've just checked it and it indeed works. That's awesome. I pushed an updated version.
You can find the relevant change [here](https://github.com/estiller/build-pki-net-azure-sample/commit/df714b0b31f0975023c2695c0637eb700594863a#diff-977c6c6704f77e1ce404ab891f900b2eR84).

Thanks!
